export const AppConstants = {
  REQUEST_POSTS: 'REQUEST_POSTS',
  REQUEST_POSTS_SUCCESS: 'REQUEST_POSTS_SUCCESS',
  REQUEST_POSTS_FAILURE: 'REQUEST_POSTS_FAILURE',

  RESET: 'RESET',
  CLICK_POST: 'CLICK_POST'
};